name: Unit Test Action
on: [push, pull_request]
jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"
      - name: Restore dependencies
        run: dotnet restore
      - name: Run Build
        run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true
      - name: Run Test
        run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Upload Coverage
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: Submarine.Core.Test/coverage.xml
